### ISSUE TITLE
更优雅地显示图文消息

### ISSUE THREAD

**Issue by catsworld** [catsworld/cqhttp#4]
@rikakomoe 你有什么建议吗

**Comment by rikakomoe** [comment]
具体？

**Comment by catsworld** [comment]
@rikakomoe 现在如果一条消息是由图文前后构成的话，在手机版上它会显示成图片靠左，消息气泡与文字等宽，图片右侧有大块留白的样子，并且如果在电脑版上看图文更是不分行（如果加入换行符，那么手机版上就会有一个巨恶心的空隙）
